# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: OpenG2P
org_slug: OpenG2P
rebel_module_groups: []
repo_description: Self Service Portal
repo_name: OpenG2P Self Service Portal
repo_slug: openg2p-self-service-portal
repo_website: https://github.com/OpenG2P/openg2p-self-service-portal
use_pyproject_toml: true
use_ruff: true

